[project]
name = "business-use-example-python"
version = "0.1.0"
description = "Example usage of the Business-Use Python SDK"
requires-python = ">=3.11"
dependencies = [
    "business-use @ file://../../sdk-py",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
